presubmits:
  - name: pre-docs-spellcheck
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/docs.git"
    spec:
      containers:
      - image: quay.io/kubermatic/codespell:1.17.1
        command:
        - make
        args:
        - spellcheck
        resources:
          requests:
            memory: 512Mi
            cpu: 0.5

  - name: pre-docs-verify-hugo
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/docs.git"
    spec:
      containers:
      - image: quay.io/kubermatic/hugo:0.75.1-0
        command:
        - "./hack/ci/verify-hugo.sh"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi

  - name: pre-docs-verify-remark-lint
    always_run: true
    decorate: true
    optional: true
    clone_uri: "ssh://git@github.com/kubermatic/docs.git"
    spec:
      containers:
      - image: quay.io/kubermatic/remark-lint:1.0.0
        command:
        - "./hack/ci/lint-markdown.sh"
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            memory: 512Mi
