presubmits:
  - name: pre-docs-verify-hugo
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/docs.git"
    spec:
      containers:
      - image: quay.io/kubermatic/hugo:0.71.1-0
        command:
        - "./hack/ci/verify-hugo.sh"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi

  - name: pre-docs-verify-remark-lint
    always_run: true
    decorate: true
    optional: true
    clone_uri: "ssh://git@github.com/kubermatic/docs.git"
    spec:
      containers:
      - image: quay.io/kubermatic/remark-lint:1.0.0
        command:
        - "./hack/ci/lint-markdown.sh"
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            memory: 512Mi

  - name: pull-docs-run-tests
     always_run: true
     decorate: true
     optional: true
     clone_uri: "ssh://git@github.com/kubermatic/docs.git"
     spec:
       containers:
       - image: quay.io/kubermatic/e2e-kind-cypress:1.1.1
         command:
         - "./hack/ci/e2e-tests.sh"
         resources:
           requests:
             cpu: 100m
             memory: 128Mi
           limits:
             memory: 512Mi
